layout_spectrum: 0.3762909534852952
typography_spectrum: 0.4554457953199744
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.7648946091067046
  lightness: 0.13848445448093116
  saturation: 0.8878413315396756
  rhythmicContrast: 0.6606199641246349
name: claudiochocolate
favicon: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
