name: claudiochocolate
favicon: null
layout_spectrum: 0.10438495129346848
typography_spectrum: 0.03286003693938255
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3534036772325635
  lightness: 0.6948272215668112
  saturation: 0.7778869620524347
  rhythmicContrast: 0.3280255163554102
purpose: []
